add stats to container logs

diff --git a/rootfs/etc/s6-overlay/scripts/api2sbs b/rootfs/etc/s6-overlay/scripts/api2sbs
--- a/rootfs/etc/s6-overlay/scripts/api2sbs
+++ b/rootfs/etc/s6-overlay/scripts/api2sbs
@@ -5,6 +5,7 @@ source /scripts/common
 
 SBS_SERVER="${SBS_SERVER:-ultrafeeder}"
 SBS_PORT="${SBS_PORT:-32006}"
+STATS_INTERVAL="${STATS_INTERVAL:-60}"
 
 if [[ -z "${LOCATIONS}" ]]; then
   "${s6wrap[@]}" echo "[FATAL] LOCATIONS is not set. Container halted"
@@ -40,11 +41,20 @@ for l in "${loc[@]}"; do
   if [[ -n "${l}" ]]; then
     { "${s6wrap[@]}" echo "[INFO] Starting data retrieval for Lat/Lon/Dist=\"$l\""
       while true; do
-        if ! curl -sSL "${API_URL}/${l//,//}" | \
-              jq -r '.ac[] | "MSG,3,1,1,\(.hex|ascii_upcase),1,'"$(date +%Y-%m-%d,%H:%M:%S,%Y-%m-%d,%H:%M:%S)"',\(.flight),\(.alt_baro),\(.gs),\(.track),\(.lat),\(.lon),,\(.squawk),,,,\(if (.alt_baro | tostring) == "ground" then "-1" else "0" end)"' | \
-              sed 's/null//;s/ground/0/' >&3; then
-          "${s6wrap[@]}" echo "[ERROR] Could not retrieve data for Lat/Lon/Dist=\"$l\""
-          break
+        if (( STATS_INTERVAL > 0 )); then        
+          if ! curl -sSL "${API_URL}/${l//,//}" | \
+                jq -r '.ac[] | "MSG,3,1,1,\(.hex|ascii_upcase),1,'"$(date +%Y-%m-%d,%H:%M:%S,%Y-%m-%d,%H:%M:%S)"',\(.flight),\(.alt_baro),\(.gs),\(.track),\(.lat),\(.lon),,\(.squawk),,,,\(if (.alt_baro | tostring) == "ground" then "-1" else "0" end)"' | \
+                sed 's/null//;s/ground/0/' | tee >&3 >>"/tmp/sbs_msgs_cache.$l"; then
+            "${s6wrap[@]}" echo "[ERROR] Could not retrieve data for Lat/Lon/Dist=\"$l\""
+            break
+          fi
+        else
+          if ! curl -sSL "${API_URL}/${l//,//}" | \
+                jq -r '.ac[] | "MSG,3,1,1,\(.hex|ascii_upcase),1,'"$(date +%Y-%m-%d,%H:%M:%S,%Y-%m-%d,%H:%M:%S)"',\(.flight),\(.alt_baro),\(.gs),\(.track),\(.lat),\(.lon),,\(.squawk),,,,\(if (.alt_baro | tostring) == "ground" then "-1" else "0" end)"' | \
+                sed 's/null//;s/ground/0/' >&3; then
+            "${s6wrap[@]}" echo "[ERROR] Could not retrieve data for Lat/Lon/Dist=\"$l\""
+            break
+          fi
         fi
         sleep "$LOOPTIME"
       done
