minor updates; move to SDR-E

diff --git a/rootfs/etc/s6-overlay/scripts/api2sbs b/rootfs/etc/s6-overlay/scripts/api2sbs
--- a/rootfs/etc/s6-overlay/scripts/api2sbs
+++ b/rootfs/etc/s6-overlay/scripts/api2sbs
@@ -19,23 +19,29 @@ fi
 
 #check if API can be reached and (if config'd) authentication is correctly set
 TEST_URL="${API_URL//\{LAT\}/90}"; TEST_URL="${TEST_URL//\{LON\}/0}"; TEST_URL="${TEST_URL//\{DIST\}/0}"
+backoff=1
 if [[ -n "$API_AUTH" ]]; then
-  if ! msg="$(curl -sSL -H "api-auth: $API_AUTH" "$TEST_URL")" \
+  while ! msg="$(curl -sSL -H --fail-with-body "api-auth: $API_AUTH" "$TEST_URL")" \
       || [[ "$msg" = '{"NO_AUTH"}' ]] \
-      || [[ "$(jq -r '.'"${json_keys[aircraft]}"'[0].'"${json_keys[registration]}"'' <<< "$msg")" != "null" ]]; then
-    "${s6wrap[@]}" echo "[FATAL] Container Halted: API_URL is wrong or API_AUTH is not set correctly. To debug, run the following command from the Linux command line:"
+      || [[ "$(jq -r '.'"${json_keys[aircraft]}"'[0].'"${json_keys[registration]}"'' <<< "$msg")" != "null" ]]; do
+    "${s6wrap[@]}" echo "[WARNING] Cannot verify API_URL or API_AUTH. Trying again in $backoff seconds. To debug, run the following command from the Linux command line:"
     "${s6wrap[@]}" echo "        curl -sSL -H \"api-auth: $API_AUTH\" \"$TEST_URL\""
-    exec sleep infinity
-  else
-    "${s6wrap[@]}" echo "[INFO] API availability and API_AUTH confirmed for $API_URL"
-  fi
+    "${s6wrap[@]}" echo "        Server response was: $msg"
+    sleep $backoff
+    backoff=$(( backoff * 2 )); if (( backoff > 60 )); then backoff=60; fi
+  done
+  "${s6wrap[@]}" echo "[INFO] API availability and API_AUTH confirmed for $API_URL"
   AUTH_HEADER="-H 'api-auth: $API_AUTH'"
-elif ! curl -sSL "$TEST_URL" >/dev/null 2>/dev/null; then
-    "${s6wrap[@]}" echo "[FATAL] Cannot reach API endpoint at $API_URL. Check your network connection and the API_URL variable and restart the container"
-    exec sleep infinity
 else
-  "${s6wrap[@]}" echo "[INFO] API availability confirmed for $API_URL"
+  while ! msg="$(curl -sSL --fail-with-body "$TEST_URL" 2>&1)"; do
+    "${s6wrap[@]}" echo "[WARNING] Cannot verify API_URL. Trying again in $backoff seconds. To debug, run the following command from the Linux command line:"
+    "${s6wrap[@]}" echo "        curl -sSL -H \"$TEST_URL\""
+    "${s6wrap[@]}" echo "        Server response was: $msg"
+    sleep $backoff
+    backoff=$(( backoff * 2 )); if (( backoff > 60 )); then backoff=60; fi
+  done
 fi
+"${s6wrap[@]}" echo "[INFO] API availability confirmed for $API_URL"
 
 readarray -d ";" -t loc <<< "${LOCATIONS// /}"
 
@@ -109,9 +115,9 @@ done
 
 "${s6wrap[@]}" echo "[INFO] Data Retrieval started for all locations"
 
-# if one of the child processes fails, start over again. No need to kill the other processes; they will be
-# killed when the service exits
+# if one of the child processes fails, start over again.
 wait -n
+pkill -P $$
 
 # be nice and close the FD
 exec 3>&-
